name: Build and deploy react + go app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    name: Build and Deploy React App
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy static web app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_GLACIER_0B32F7703 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/Week5/vite-project"
          output_location: "dist"
          
  run_tests:
    runs-on: ubuntu-latest
    name: Run Cypress Tests
    needs: build_and_deploy_frontend
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: Week8/

  build_backend:
    runs-on: "ubuntu-latest"
    name: Build Go App 

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_cb1ad1cd1ea5412b96c5d3032493bd41 }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          context: Week5/backend/
          push: true
          tags: clooux/obiekt-go:${{ github.sha }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_TOKEN }}

  deploy_backend:
    runs-on: ubuntu-latest
    name: Deploy Go App
    needs: build_backend
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy Go to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "walka-go"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_ad95985068c14725a858c768edaeba62 }}
          images: "clooux/obiekt-go:${{ github.sha }}"

  send_email:
    needs: [run_tests, deploy_backend]
    name: Send email
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3.7.2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.GMAIL }}
          subject: Build finished
          body: Build job of ${{github.repository}} completed successfully!
          to: ${{ secrets.EMAIL }}
          from: ${{ secrets.EMAIL }}
